spring.application.name=WebBackend
phoa.store.tdb2-dir=./data/tdb2
phoa.admin.reset-token=blabla


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexxdominte@gmail.com
spring.mail.password=zrab rnjo drmq lcck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
